services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5434:5432 # enables connecting locally via psql
    environment:
      POSTGRES_DB: quests_db
      POSTGRES_HOST_AUTH_METHOD: trust